//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnCoReWebPage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.ArticleTags = new HashSet<ArticleTag>();
            this.Commentaires = new HashSet<Commentaire>();
        }
    
        public System.Guid Id { get; set; }
        public string Image { get; set; }
        public string Titre { get; set; }
        public string Libelle { get; set; }
        public System.DateTime Parution { get; set; }
        public System.Guid CategorieId { get; set; }
        public System.Guid UtilisateurId { get; set; }
        public bool Valider { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual ICollection<ArticleTag> ArticleTags { get; set; }
        public virtual ICollection<Commentaire> Commentaires { get; set; }
    }
}
