//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnCoReWebPage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentaire
    {
        public System.Guid Id { get; set; }
        public System.DateTime Date { get; set; }
        public string CommentateurNomPrenoms { get; set; }
        public string CommentateurEmail { get; set; }
        public string Libelle { get; set; }
        public bool Valider { get; set; }
        public System.Guid ArticleId { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
