//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnCoReWebPage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordRequest
    {
        public System.Guid Id { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.Guid UtilisateurId { get; set; }
    }
}
