//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnCoReWebPage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Utilisateurs = new HashSet<Utilisateur>();
        }
    
        public System.Guid Id { get; set; }
        public string Nom { get; set; }
        public bool Article { get; set; }
        public bool Categorie { get; set; }
        public bool Role_ { get; set; }
        public bool Utilisateur { get; set; }
        public bool Valider_Article { get; set; }
        public bool Valider_Commentaire { get; set; }
    
        public virtual ICollection<Utilisateur> Utilisateurs { get; set; }
    }
}
